### ISSUE TITLE
create login / index page

### ISSUE THREAD

**Issue by dianaberna** [team1-td/IAM-Frontend#4]
_Estimated time: 10m_
Time: 30m

**Comment by Ishtraodd** [comment]
[COMPLETED] Base html and css structure. I've also added the small js code for view/hide the password typed by the user in the appropriate field. Esimated time: 10 minutes. Real time: 30 minutes, but honestly I have to admit that this delay was due to my doubts about correct github procedure, and most of that time it is in fact spent by me going through the steps regarding the correct way to use github.
